trigger:
- main

pool:
  name: MySelfHostedPool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    dotnet build --configuration Release
    dotnet test
    dotnet publish --configuration Release --output publishOutput
  displayName: 'Build and test .NET Core project'
